name: jalsetu
description: A new Flutter project for JalSetu.

# This line ensures the app is not published to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  google_sign_in: ^7.2.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  http: ^1.1.0
  
  # --- START: LOCALIZATION ADDITIONS ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2 # FIXED: Upgraded version to satisfy Flutter SDK's pinned requirement (0.20.2).
  flutter_gen: ^5.12.0
  intl_utils: ^2.8.12
  # --- END: LOCALIZATION ADDITIONS ---


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4 
  change_app_package_name: "^1.1.0"

# --- START: LOCALIZATION & ASSETS CONFIGURATION ---
flutter:
  # 🎯 FINAL FIX: This flag is CRUCIAL for i18n: it tells Flutter to auto-generate translation code
  generate: true 
  
  uses-material-design: true
  assets:
    - assets/images/
    # If you had translation files manually stored, they'd go here. 
    # But with flutter_gen, the ARB files are picked up via the l10n.yaml.
flutter_gen: # <--- MUST be aligned with 'flutter:' and 'name:'
  output: lib/gen/

# --- END: LOCALIZATION & ASSETS CONFIGURATION ---

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/jalsetu_logo.png" 
  min_sdk_android: 21
