name: jalsetu
description: A new Flutter project for JalSetu.

# This line ensures the app is not published to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  http: ^1.1.0
  
  # --- START: LOCALIZATION ADDITIONS ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 # Use 0.19.0 for better compatibility with Flutter 3.x
  # --- END: LOCALIZATION ADDITIONS ---


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1" 
  change_app_package_name: "^1.1.0"

# --- START: LOCALIZATION & ASSETS CONFIGURATION ---
flutter:
  # This flag is CRUCIAL for i18n: it tells Flutter to auto-generate translation code
  flutter_gen: true 
  uses-material-design: true
  assets:
    - assets/images/
    # If you had translation files manually stored, they'd go here. 
    # But with flutter_gen, the ARB files are picked up via the l10n.yaml.

# --- END: LOCALIZATION & ASSETS CONFIGURATION ---

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/jalsetu_logo.png" 
  min_sdk_android: 21
