// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw1Q5iHA4OZ5sEHW7I0LtlTd20O3QM0Zg',
    appId: '1:484613520075:web:9bcc2e4966fe95818bb94e',
    messagingSenderId: '484613520075',
    projectId: 'jalsetu-3cede',
    authDomain: 'jalsetu-3cede.firebaseapp.com',
    storageBucket: 'jalsetu-3cede.firebasestorage.app',
    measurementId: 'G-RPS9LT6VJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEVxFtznvXMmtqXpI_-raN2JI-UPf6Jy4',
    appId: '1:484613520075:android:e8dd433aeed914418bb94e',
    messagingSenderId: '484613520075',
    projectId: 'jalsetu-3cede',
    storageBucket: 'jalsetu-3cede.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw1Q5iHA4OZ5sEHW7I0LtlTd20O3QM0Zg',
    appId: '1:484613520075:web:9d13e467e76b6d598bb94e',
    messagingSenderId: '484613520075',
    projectId: 'jalsetu-3cede',
    authDomain: 'jalsetu-3cede.firebaseapp.com',
    storageBucket: 'jalsetu-3cede.firebasestorage.app',
    measurementId: 'G-2RLCNDZSQ1',
  );

}